#!/usr/bin/env bash


function cycle_v1() {
	local direction="${1}"
	local fallback="${2}"
	yabai -m window --focus "${direction}" || yabai -m window --focus "${fallback}"
}

function cycle_v2() {
  test "${1}" = "reverse" || is_reversed="| reverse"
  
  yabai -m query --spaces --space \
  | jq -re ".index" \
  | xargs -I{} yabai -m query --windows --space {} \
  | jq -sre 'add | map(select(."is-minimized" == false)) | map(select(."app" != "Emoji & Symbols")) | sort_by(.display, .frame.y, .frame.x, .id) '"${is_reversed}"' | nth(index(map(select(."has-focus" == true))) - 1).id' \
  | xargs -I{} yabai -m window --focus {}
}

function cyclei_v3() {
	local direction=${1}
	
	yabai -m query --windows --window stack.first 2>&1 > /dev/null
	local is_stacked=$?

	if [[ $is_stacked -eq 0 ]]; then
		[[ "${direction}" == "forward" ]] && yabai -m window --focus stack.next || yabai -m window --focus stack.first
		[[ "${direction}" == "reverse" ]] && yabai -m window --focus stack.prev || yabai -m window --focus stack.last
	fi

}


if [[ "${1}" == "forward" ]]; then
	cycle_v2
fi

if [[ "${1}" == "reverse" ]]; then
	cycle_v2 reverse
fi
